/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RotButton {
        "as": string;
        "disabled": boolean;
        "href": string;
        "target": string;
        "type": string;
        "variant": string;
    }
}
declare global {
    interface HTMLRotButtonElement extends Components.RotButton, HTMLStencilElement {
    }
    var HTMLRotButtonElement: {
        prototype: HTMLRotButtonElement;
        new (): HTMLRotButtonElement;
    };
    interface HTMLElementTagNameMap {
        "rot-button": HTMLRotButtonElement;
    }
}
declare namespace LocalJSX {
    interface RotButton {
        "as"?: string;
        "disabled"?: boolean;
        "href"?: string;
        "target"?: string;
        "type"?: string;
        "variant"?: string;
    }
    interface IntrinsicElements {
        "rot-button": RotButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rot-button": LocalJSX.RotButton & JSXBase.HTMLAttributes<HTMLRotButtonElement>;
        }
    }
}
